[font]
size = 10.0

[font.bold]
family = "GeistMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "GeistMono Nerd Font"
style = "Bold"

[font.italic]
family = "GeistMono Nerd Font"
style = "Regular"

[font.normal]
family = "GeistMono Nerd Font"
style = "Regular"
