noIndentBlock:
  block:
    begin: '%\hstartnoindent'
    end: '%\hendnoindent'
    lookforthis: 0

removeTrailingWhitespace: 1
fileContentsEnvironments:
  filecontents: 0
  filecontents*: 0
indentPreamble: 0
preambleCommandsBeforeEnvironments: 0

lookForAlignDelims:
  tabular: 1
  tabularx: 1
  longtable: 1
  array: 1
  matrix: 1
indentAfterItems:
  itemize: 1
  itemize*: 1
  enumerate: 1
  enumerate*: 1
  description: 1
  description*: 1
  list: 1
  tabular: 1
  tabularx: 1
  longtable: 1
  array: 1
  matrix: 1

specialBeginEnd:
  displayMath:
    begin: (?<!\\)\\\[ # \[ but *not* \\[
    end: \\\] # \]
    lookForThis: 1
  inlineMath:
    begin: (?<!\$)(?<!\\)\$(?!\$) # $ but *not* \$ or $$
    end: (?<!\\)\$(?!\$) # $ but *not* \$ or $$
    lookForThis: 1
  displayMathTeX:
    begin: \$\$ # $$
    end: \$\$ # $$
    lookForThis: 1
  leftRightSquare:
    begin: '\\left\['
    end: '\\right\]'
    lookForThis: 1
  If:
    begin: '\\If'
    middle:
      - '\\ElsIf'
      - '\\Else'
    end: '\\EndIf'
    lookForThis: 1
  specialBeforeCommand: 0

# indentAfterHeadings:
#   paragraph:
#     indentAfterThisHeading: 1
#     level: 1

noAdditionalIndent:
  document: 0
  item: 1
noAdditionalIndentGlobal:
  environments: 0
  commands: 0
  optionalArguments: 0
  mandatoryArguments: 0
  ifElseFi: 0
  items: 0
  specialBeginEnd: 0
  afterHeading: 0
indentRulesGlobal:
  environments: "\t"
  commands: "\t"
  optionalArguments: "\t"
  mandatoryArguments: "\t"
  ifElseFi: "\t"
  items: "\t"
  specialBeginEnd: "\t"
  afterHeading: 1
